apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
 replicas: 1
 selector:
   app: prometheus
   deploymentconfig: prometheus
 strategy:
   type: Rolling
 template:
   metadata:
     labels:
       app: prometheus
       deploymentconfig: prometheus
   spec:
     containers:
     - args:
       - -storage.local.retention=6h
       - -storage.local.memory-chunks=500000
       - -config.file=/etc/prometheus/conf/prometheus.yml
       - -web.console.libraries=/etc/prometheus/console_libraries
       - -web.console.templates=/etc/prometheus/console
       image: prom/prometheus:latest
       imagePullPolicy: Always
       name: prometheus
       ports:
       - containerPort: 9090
         name: web
         protocol: TCP
       volumeMounts:
       - mountPath: /prometheus
         name: prometheus-1
       - mountPath: /etc/prometheus/conf
         name: prometheusconf
     dnsPolicy: ClusterFirst
     restartPolicy: Always
     serviceAccountName: prometheus
     volumes:
     - emptyDir: {}
       name: prometheus-1
     - configMap:
         name: prometheusconfig
       name: prometheusconf
 triggers:
 - type: ConfigChange
 - imageChangeParams:
     automatic: true
     containerNames:
     - prometheus
     from:
       kind: ImageStreamTag
       name: prometheus:latest
   type: ImageChange